# $Header: /space/home/eng/cjm/cvs/libdprt-grope/Makefile.common,v 1.1 2005-11-29 15:48:07 cjm Exp $

GROPE_HOME		= grope
LIBDPRT_GROPE_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(GROPE_HOME)
LIBDPRT_GROPE_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(GROPE_HOME)
LIBDPRT_GROPE_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(GROPE_HOME)

#
# $Log: not supported by cvs2svn $
#
